export const KEY = 'weather-page';

export enum WEATHER_PAGE_ACTION_TYPES {
  SEARCH_WEATHER = 'SEARCH_WEATHER',
  SEARCH_WEATHER_SUCCESS = 'SEARCH_WEATHER_SUCCESS',
  SEARCH_WEATHER_FAILED = 'SEARCH_WEATHER_FAILED',

  DELETE_SEARCH_RESULT = 'DELETE_SEARCH_RESULT',
}
